for(i=0; i<=20; i++){

  var genap = "Bilangan Genap";
  var ganjil = i

  if(i==0)
  console.log(i)
  if(i==1)
  console.log(i)
  if(i==3)
  console.log(i)
  if(i==5)
  console.log(i)
  if(i==7)
  console.log(i)
  if(i==9)
  console.log(i)
  if(i==11)
  console.log(i)
  if(i==13)
  console.log(i)
  if(i==15)
  console.log(i)
  if(i==17)
  console.log(i)
  if(i==19)
  console.log(i)

  if(i==2)
  console.log(genap)
  if(i==4)
  console.log(genap)
  if(i==6)
  console.log(genap)
  if(i==8)
  console.log(genap)
  if(i==10)
  console.log(genap)
  if(i==12)
  console.log(genap)
  if(i==14)
  console.log(genap)
  if(i==16)
  console.log(genap)
  if(i==18)
  console.log(genap)
  if(i==20)
  console.log(genap)

}